# Reference snapshot of the published Homebrew formula.
#
# Not consumed by any tool. The live formulas are generated by
# cli/_tool/fwc-deploy-brew.sh:
#   - `local`   -> inline formula written into the local tap (file:// tarball)
#   - `publish` -> this shape written into finfra/homebrew-tap (GitHub release tarball)
# This file exists so readers can see what `brew install` actually pulls in.
#
# Issue89: the previous copy carried a hardcoded `version "1.0.0"` that no tool
# read and that matched neither VERSION nor the shipped bundle. The field is
# dropped on purpose - Homebrew scans the version from the URL basename
# (fWarrangeCli-{VERSION}.tar.gz), so VERSION stays the single source of truth.
class FwarrangeCli < Formula
  desc "Window layout management daemon for fWarrange"
  homepage "https://github.com/Finfra/fWarrange_public"
  # version is scanned from the URL basename (fWarrangeCli-1.1.3.tar.gz)
  url "https://github.com/Finfra/fWarrange_public/releases/download/cli-v1.1.3/fWarrangeCli-1.1.3.tar.gz"
  # sha256 is regenerated per release by fwc-deploy-brew.sh publish
  sha256 "e8f1d5d62981cac52e786cfec2caeca6d7b4062167ab5dfce198dd65d38700e7"
  # Source: Apache-2.0. Official builds are also subject to DISTRIBUTION-TERMS.md (see caveats)
  license "Apache-2.0"

  depends_on :macos

  def install
    # Tarball contains pre-built fWarrangeCli.app (Apple Development signature preserved).
    # Brew sandbox restricts keychain access, so copy as-is without rebuilding.
    prefix.install "fWarrangeCli.app"
  end

  service do
    run [opt_prefix/"fWarrangeCli.app/Contents/MacOS/fWarrangeCli"]
    keep_alive successful_exit: false
    log_path var/"log/fwarrange-cli.log"
    error_log_path var/"log/fwarrange-cli.err.log"
    process_type :interactive
  end

  def caveats
    <<~EOS
      fWarrangeCli requires Accessibility permissions.

      To enable auto-start after installation:
        brew services start finfra/tap/fwarrange-cli

      To grant Accessibility permissions:
        System Settings > Privacy & Security > Accessibility > fWarrangeCli

      If TCC permissions are corrupted, reset via Xcode Debug path: /run tcc

      License: source code is Apache-2.0. This official build is free for personal use,
      education, non-profits, open source and other organizations up to 250 concurrent copies.
      Terms: https://github.com/Finfra/fWarrange_public/blob/main/DISTRIBUTION-TERMS.md
    EOS
  end

  test do
    assert_predicate prefix/"fWarrangeCli.app/Contents/MacOS/fWarrangeCli", :exist?
  end
end
